### ISSUE TITLE
Unable to reach GitHub 

### ISSUE THREAD

**Issue by jeronimo13** [shivammathur/node-docker#7]
```
spc --php-version "7.4" \
              --extensions "mbstring, openssl, ffi" \
              --ini-values "post_max_size=256M, max_execution_time=180" \
              --tools "composer, phpunit"
```
fails with:
```
Unable to reach GitHub 
Please check your internet connection 
```

I dig a bit and found that `curl` command output: `error setting certificate verify locations`

I patched the container after `docker pull` with
```
apt-get update
apt-get install ca-certificates
```
and it solves the problem, so that I can `spc` successfully, but I believe it's not ideal and I barely understand what's going on.

**Comment by shivammathur** [comment]
Fixed in https://github.com/shivammathur/node-docker/commit/937a0f3fd94c7fc31762dcf6dd5b2383295a8fdf
You can pull the image again and run spc, it should work now.

Also I would recommend using non slim images for `spc` as those have the required packages for it. On slim images it installs them when you run `spc` for the first time.
